version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
