[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
name = "FPbase"
version = "0.1.0"
description = "The Fluorescent Protein Database"
authors = [{ name = "Talley Lambert", email = "talley.lambert@gmail.com" }]
requires-python = "==3.11.3"
license = { text = "GPL-3.0" }
dependencies = [
    "pytz==2023.3",
    "python-slugify==8.0.1",
    "Pillow==9.5.0",
    "rcssmin==1.1.1",
    "argon2-cffi==21.3.0",
    "whitenoise[brotli]==6.4.0",
    "redis==4.5.4",
    "psycopg2==2.9.6",
    "django==4.2.1",
    "django-environ==0.10.0",
    "django-model-utils==4.3.1",
    "django-allauth==0.54.0",
    "django-redis==5.2.0",
    "django-crispy-forms==1.13.0",
    "djangorestframework==3.14.0",
    "drf-spectacular==0.26.2",
    "djangorestframework-csv==2.1.1",
    "django-recaptcha==3.0.0",
    "sentry-sdk==1.21.1",
    "biopython==1.81",
    "pandas==2.0.1",
    "parasail==1.3.4",
    "habanero==1.2.3",
    "django-filter==23.2",
    "django-reversion==5.0.4",
    "django-reversion-compare==0.16.1",
    "tablib==3.4.0",
    "scipy==1.10.1",
    "dnspython==2.3.0",
    "django-anymail==10.0",
    "django-autocomplete-light==3.9.4",
    "django-avatar==7.1.1",
    "numpy==1.24.3",
    "matplotlib==3.7.1",
    "django-mptt==0.14.0",
    "django-webpack-loader==1.8.1",
    "google-api-python-client==2.86.0",
    "oauth2client==4.1.3",
    "algoliasearch-django==3.0.0",
    "celery[redis]==5.2.7",
    "graphene==3.2.2",
    "graphene-django==3.0.2",
    "graphene-django-optimizer==0.9.1",
    "django-graphql-jwt==0.3.4",
    "django-cors-headers==4.0.0",
    # ===== not needed in development =====
    "gunicorn==20.1.0",
    "django-storages[boto3]==1.13.2",
]

[tool.pdm.dev-dependencies]
dev = [
    "Werkzeug[watchdog]==2.3.4",
    "ipdb==0.13.13",
    "watchfiles==0.19.0",
    "pytest==7.3.1",
    "pytest-sugar==0.9.7",
    "pytest-cov==4.0.0",
    "factory-boy==3.2.1",
    "django-test-plus==2.2.1",
    "django-coverage-plugin==3.0.0",
    "pytest-django==4.5.2",
    "selenium==4.9.1",
    "flake8==6.0.0",
    "flake8-black==0.3.6",
    "coverage==7.2.5",
    "black==23.3.0",
    "pylint-django==2.5.3",
    "pre-commit==3.3.1",
    "mypy==1.2.0",
    "django-stubs==4.2.0",
    "djangorestframework-stubs==3.14.0",
    "pdbpp==0.10.3",
    "django-debug-toolbar==4.0.0",
    "django-extensions==3.2.1",
]

[tool.pdm.scripts]
server = {cmd = "python manage.py runserver", help = "Run django server"}
pgpull = {cmd = "python manage.py pgpull", help = "Sync database"}
migrate = {cmd = "python manage.py migrate", help = "Migrate database"}


# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=config.settings.test --reuse-db --cov-config=pyproject.toml"
python_files = ["tests.py", "test_*.py"]
norecursedirs = ["node_modules"]
filterwarnings = [
    "error",
    "ignore:SelectableGroups dict interface is deprecated::kombu",
    "ignore:The DEFAULT_FILE_STORAGE setting is deprecated::",
    "ignore:django.core.files.storage.get_storage_class is deprecated::",
    "ignore::DeprecationWarning:pkg_resources",
    "ignore::ResourceWarning",
]


# ==== Coverage ====
[tool.coverage.run]
source = ["fpbase", "proteins", "references", "fpseq", "favit"]
omit = ["*/migrations/*", "*/tests/*", "proteins/management/**"]
# plugins = ["django_coverage_plugin"]


# ==== black ====
[tool.black]
line-length = 119
target-version = ['py311']


# ==== ruff ====
[tool.ruff]
line-length = 119
target-version = "py311"
exclude = ['*/migrations/*', '*/static/CACHE/*', '.venv']
select = [
    "F", # Pyflakes
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "I", # isort
    # "N",   # pep8-naming
    "UP",  # pyupgrade
    "YTT", # flake8-2020
    # "S",   # flake8-bandit
    "B", # flake8-bugbear
    # "A",   # flake8-builtins
    "C4", # flake8-comprehensions
    # "DTZ", # flake8-datetimez
    "DJ", # flake8-django
    # "PTH", # flake8-pathlib
    "RUF", # Ruff-specific rules
]
ignore = [
    "B905", # `zip()` without an explicit `strict=` parameter
    "S101", # Use of assert detected.
]
[tool.ruff.per-file-ignores]
"**/tests/*" = ["S"]
"references/admin.py" = ["S308"]
"config/settings/*" = ["F405"]

[tool.isort]
profile = "black"
line_length = 119
known_first_party = ["fpbase", "config"]
skip = ["venv/"]
skip_glob = ["**/migrations/*.py"]


# ==== mypy ====
[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[[tool.mypy.overrides]]
# Django migrations should not produce any errors:
module = "*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "config.settings.test"


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
