['name: acanFP, row: 8, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'same sequence name mismatch between aceGFP_G222E (Colorless Form) and aceGFP_G222E (UV-Photoconverted Green Form)',
 'GenBank mismatch between amajGFP and amajGFP',
 'same sequence name mismatch between amilCFP and amilFP490',
 'same sequence name mismatch between amilFP513 and amilGFP',
 'same sequence name mismatch between amilFP593 and amilRFP',
 'GenBank mismatch between arFP499 and asFP499',
 'UniProt mismatch between arFP499 and asFP499',
 'same sequence name mismatch between arFP499 and asFP499',
 'name: asFP499 , row: 74, * agg\n  * Select a valid choice. d/Trimer is not one of the available choices.',
 'GenBank mismatch between arFP499 and asFP499',
 'UniProt mismatch between arFP499 and asFP499',
 'same sequence name mismatch between arFP499 and asFP499',
 'name: asFP499 , row: 75, * genbank\n  * Ensure this value has at most 12 characters (it has 20).',
 'same sequence name mismatch between asCP (A148S) and asFP595 (A143S)',
 'same sequence name mismatch between asFP595 (S158V) and asulCP',
 'GenBank mismatch between asCP562 and asulCP562',
 'same sequence name mismatch between asCP562 and asulCP562',
 'GenBank mismatch between arFP499 and asulGFP',
 'UniProt mismatch between arFP499 and asulGFP',
 'same sequence name mismatch between arFP499 and asulGFP',
 'same sequence name mismatch between avGFP (1W7T) and avGFP (1W7U)',
 'name: avGFP480, row: 92, * seq\n  * Invalid letter(s) found in amino acid sequence: )4-(',
 'same sequence name mismatch between avGFP (1W7T) and avGFP508',
 'same sequence name mismatch between avGFP (1W7T) and avGFP508',
 'name: avGFP509, row: 95, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'name: avGFP510, row: 96, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'name: avGFP514, row: 97, * chromophore\n  * Ensure this value has at most 5 characters (it has 13).\n* seq\n  * Invalid letter(s) found in amino acid sequence: )3U(-O',
 'name: avGFP523, row: 98, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'same sequence name mismatch between BFPms1 (Apo) and BFPms1 (Cu)',
 'same sequence name mismatch between BFPms1 (Apo) and BFPms1 (Zn)',
 'same sequence name mismatch between cgCP (C148S) and cgigCP',
 'name: cgigGFP, row: 136, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'same sequence name mismatch between cFP484 and clavGFP',
 'same sequence name mismatch between cpasCP and cpCP (wild-type)',
 'same sequence name mismatch between cpT-Sapphire 145-144 and cpT-Sapphire 174-173',
 'GenBank mismatch between dendGFP and dendRFP',
 'same sequence name mismatch between dendGFP and dendRFP',
 'same sequence name mismatch between Dreiklang and Dreiklang (Off State)',
 'same sequence name mismatch between Dreiklang and Dreiklang (On State)',
 'same sequence name mismatch between Dronpa-2 and Dronpa-M159T',
 'GenBank mismatch between discRFP and DsRed',
 'same sequence name mismatch between discRFP and DsRed',
 'same sequence name mismatch between discRFP and Dsred (wild-type)',
 'same sequence name mismatch between discRFP and DsRed (wild-type)',
 'same sequence name mismatch between DsRed.T3 and Dsred.T4',
 'name: DstC1, row: 245, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'GenBank mismatch between dstrCyFP and dstrGFP',
 'same sequence name mismatch between dstrCyFP and dstrGFP',
 'name: dstrGFP, row: 247, * genbank\n  * Protein with this Genbank Accession already exists.',
 'name: echFP, row: 267, * seq\n  * Invalid letter(s) found in amino acid sequence: BX',
 'same sequence name mismatch between eGFP203C and eGFP205C',
 'same sequence name mismatch between DstC1 and Enhanced Red Fluorescent Protein R+',
 'name: EosFP Wild-type (Before and After Photoconversion), row: 284, * agg\n  * Select a valid choice. t  is not one of the available choices.',
 'same sequence name mismatch between eqFP611 and equaRFP',
 'same sequence name mismatch between cpCitrine and EYFP (V68L/Q69K)',
 'same sequence name mismatch between eqFP480 and FP480',
 'name: Fpaagar, row: 307, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'name: FPmann, row: 310, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'name: FPmcavgr7.7, row: 311, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'name: FPrfl2.3, row: 312, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'same sequence name mismatch between GCaMP2 (Dimer) and GCaMP2 (Monomer)',
 'name: GFP  (Y66p-amino-F), row: 326, * chromophore\n  * Ensure this value has at most 5 characters (it has 13).\n* seq\n  * Invalid letter(s) found in amino acid sequence: )-O(',
 'same sequence name mismatch between EGFP (Y66L) and GFP (F64L/S65T/Y66L)',
 'same sequence name mismatch between avGFP and GFP (F64L/T203Y/H231L)',
 'same sequence name mismatch between GFP (S65T/H148D) and GFP (S65T/H148D/Q80R)',
 'same sequence name mismatch between GFP (S65T) and GFP (S65T/Q80R)',
 'same sequence name mismatch between GFP (S65T) and GFP (S65T/Q80R)',
 'name: GFP (Y66p-bromo-F), row: 370, * chromophore\n  * Ensure this value has at most 5 characters (it has 13).\n* seq\n  * Invalid letter(s) found in amino acid sequence: )B(-O',
 'name: GFP (Y66p-iodo-F), row: 371, * chromophore\n  * Ensure this value has at most 5 characters (it has 13).\n* seq\n  * Invalid letter(s) found in amino acid sequence: )-O(',
 'name: GFP (Y66p-methoxy-F), row: 372, * chromophore\n  * Ensure this value has at most 5 characters (it has 13).\n* seq\n  * Invalid letter(s) found in amino acid sequence: )X(-O',
 'same sequence name mismatch between gtCP (N148S) and gtenCP',
 'GenBank mismatch between gtCP (N148S) and gtenCP',
 'same sequence name mismatch between gtCP (N148S) and gtenCP',
 'same sequence name mismatch between hcCP (C148S) and hcriCP',
 'GenBank mismatch between HriCFP and HriGFP',
 'UniProt mismatch between HriCFP and HriGFP',
 'same sequence name mismatch between HriCFP and HriGFP',
 'same sequence name mismatch between EBFP2 and iq-EBFP2',
 'same sequence name mismatch between IrisFP (Distorted Chromophore) and IrisFP (Planar Chromophore)',
 'same sequence name mismatch between anm2CP and Jred',
 'same sequence name mismatch between asulFP and KFP1',
 'name: KO , row: 446, * agg\n  * Select a valid choice. d/t is not one of the available choices.',
 'name: KO (Hypothetical Protein), row: 447, * agg\n  * Select a valid choice. d/t is not one of the available choices.',
 'same sequence name mismatch between laRFP and laRFP (Deletion on Ser83)',
 'same sequence name mismatch between LEA and LEA (Q38A)',
 'GenBank mismatch between afraGFP and lscuFP',
 'UniProt mismatch between afraGFP and lscuFP',
 'same sequence name mismatch between afraGFP and lscuFP',
 'same sequence name mismatch between iq-mApple and mApple',
 'name: mcavFP, row: 499, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'GenBank mismatch between McaG2 and mcavGFP2',
 'same sequence name mismatch between McaG2 and mcavGFP2',
 'GenBank mismatch between mcavRFP and mcavRFP',
 'GenBank mismatch between mcavCyFP and mcCFP',
 'same sequence name mismatch between mcavCyFP and mcCFP',
 'name: mcCFP, row: 504, * agg\n  * Select a valid choice. Trimer is not one of the available choices.',
 'same sequence name mismatch between iq-mCerulean3 and mCerulean3',
 'GenBank mismatch between mc2 and mfavFP',
 'UniProt mismatch between mc2 and mfavFP',
 'same sequence name mismatch between mc2 and mfavFP',
 'same sequence name mismatch between iq-mKate2 and mKate2',
 'same sequence name mismatch between mKO and mKO (pH 6.0)',
 'same sequence name mismatch between mKO2 and mKOk',
 'same sequence name mismatch between mPlumAYC-E16P (Green) and mPlumAYC-E16P (Red)',
 'same sequence name mismatch between mStrawberry (pH 10.5) and mStrawberry (pH 9.5)',
 'same sequence name mismatch between mTFP.07 and mTFP0.7',
 'same sequence name mismatch between iq-mVenus and mVenus',
 'same sequence name mismatch between PATagRFP1297 and PATagRFP1314',
 'same sequence name mismatch between KillerRed and Photobleached KillerRed',
 'same sequence name mismatch between copGFP and ppluGFP2',
 'same sequence name mismatch between PS-CFP and PS-CFP2',
 'same sequence name mismatch between psRFP (Off State) and psRFP (On State)',
 'name: psupFP, row: 706, * seq\n  * Invalid letter(s) found in amino acid sequence: BX',
 'GenBank mismatch between ptilGFP and ptilGFP',
 'name: rfloGFP2, row: 711, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'name: rfloRFP, row: 712, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'GenBank mismatch between rmueGFP and rmueGFP',
 'same sequence name mismatch between roGFP1 and roGFP2',
 'same sequence name mismatch between rsTagRFP and rsTagRFP (OFF State)',
 'same sequence name mismatch between H9 and Sapphire',
 'name: scubGFP1, row: 750, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'name: scubGFP2, row: 751, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'name: sfGFPF145AzF (Irradiated State), row: 754, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'name: sfGFPY66AzF (Before and After Irradiation), row: 755, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'same sequence name mismatch between GFP (F64L/K238N) and sg11',
 'same sequence name mismatch between GFP (F64L/Y66H) and sg42',
 'same sequence name mismatch between GFP (F64L/Y66H/V163A) and sg50',
 'name: Superfolder GFP, row: 775, * agg\n  * Select a valid choice. m  is not one of the available choices.',
 'GenBank mismatch between SCFP1 and SYFP2',
 'same sequence name mismatch between SCFP1 and SYFP2',
 'name: sympFP, row: 778, * seq\n  * Invalid letter(s) found in amino acid sequence: X',
 'same sequence name mismatch between cpT-Sapphire 145-144 and T-Sapphire',
 'same sequence name mismatch between DsRed-Express and T1',
 'same sequence name mismatch between eqFP578f and tdKatushka2',
 'same sequence name mismatch between YFP (H146G) and YFP (H148G)',
 'same sequence name mismatch between YFP (H148G) and YFP (H148Q)',
 'same sequence name mismatch between YFP (H148G) and YFP (H148Q)',
 'same sequence name mismatch between YFP (H148G) and YFP (H148Q)',
 'same sequence name mismatch between zFP506 and zoanGFP',
 'GenBank mismatch between zFP506 and zoanGFP',
 'same sequence name mismatch between zFP506 and zoanGFP',
 'GenBank mismatch between zoan2RFP and zoanRFP',
 'same sequence name mismatch between zoan2RFP and zoanRFP',
 'same sequence name mismatch between zFP538 (wild-type) and zoanYFP',
 'GenBank mismatch between zFP538 (wild-type) and zoanYFP',
 'same sequence name mismatch between zFP538 (wild-type) and zoanYFP',
 'same sequence name mismatch between zFP538 (wild-type) and zYFP538']