# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-12 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0002_auto_20180312_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='oser',
            field=models.FloatField(blank=True, help_text='OSER score', null=True),
        ),
    ]
