# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0003_protein_oser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fretpair',
            unique_together=set([('donor', 'acceptor')]),
        ),
    ]
