# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0004_auto_20180315_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bleachmeasurement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bleachmeasurement_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bleachmeasurement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bleachmeasurement_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fretpair',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fretpair_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fretpair',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fretpair_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organism',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organism_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organism',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organism_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='protein',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protein_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='protein',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protein_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
