# Generated by Django 2.0.5 on 2018-05-13 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proteins', '0006_auto_20180512_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='camera',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dye',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dye_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dye',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dye_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filter_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='light',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='light_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='light',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='light_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
