# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0009_auto_20180430_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='part',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='dye',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='dye',
            name='part',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='filter',
            name='part',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='light',
            name='part',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='spectrum',
            name='subtype',
            field=models.CharField(blank=True, choices=[('ex', 'Excitation'), ('ab', 'Absorption'), ('em', 'Emission'), ('2p', 'Two Photon Absorption'), ('bp', 'Bandpass'), ('bx', 'Bandpass (Excitation)'), ('bm', 'Bandpass (Emission)'), ('sp', 'Shortpass'), ('lp', 'Longpass'), ('bs', 'Beamsplitter'), ('qe', 'Quantum Efficiency'), ('pd', 'Power Distribution')], db_index=True, max_length=2, verbose_name='Spectra Subtype'),
        ),
    ]
