# Generated by Django 2.0.7 on 2018-07-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0013_auto_20180718_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticalconfig',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optical_configs', to='proteins.Camera'),
        ),
        migrations.AlterField(
            model_name='opticalconfig',
            name='light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optical_configs', to='proteins.Light'),
        ),
    ]
