# Generated by Django 2.0.6 on 2018-07-20 19:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0014_auto_20180718_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microscope',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='microscope',
            name='managers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='opticalconfig',
            name='managers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='proteincollection',
            name='managers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None),
        ),
    ]
