# Generated by Django 2.0.7 on 2018-07-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0015_auto_20180720_1921"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="microscope",
            name="bs_filters",
        ),
        migrations.RemoveField(
            model_name="microscope",
            name="cameras",
        ),
        migrations.RemoveField(
            model_name="microscope",
            name="em_filters",
        ),
        migrations.RemoveField(
            model_name="microscope",
            name="ex_filters",
        ),
        migrations.RemoveField(
            model_name="microscope",
            name="lasers",
        ),
        migrations.RemoveField(
            model_name="microscope",
            name="lights",
        ),
        migrations.AddField(
            model_name="opticalconfig",
            name="comments",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
