# Generated by Django 2.0.6 on 2018-07-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0017_auto_20180722_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='cofactor',
            field=models.CharField(blank=True, choices=[('bv', 'Biliverdin')], max_length=2),
        ),
    ]
