# Generated by Django 2.0.7 on 2018-07-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0018_protein_cofactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="cofactor",
            field=models.CharField(
                blank=True,
                choices=[("bv", "Biliverdin"), ("fl", "Flavin")],
                help_text="Required for fluorescence",
                max_length=2,
            ),
        ),
    ]
