# Generated by Django 2.0.9 on 2018-10-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20180804_0203'),
        ('proteins', '0026_bleachmeasurement_cell_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='osermeasurement',
            unique_together={('protein', 'reference')},
        ),
    ]
