# Generated by Django 2.0.9 on 2018-10-12 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0003_auto_20180804_0203'),
        ('proteins', '0027_auto_20181011_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('approved', 'approved'), ('flagged', 'flagged'), ('rejected', 'rejected')], default='approved', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('content', models.TextField(help_text='Brief excerpt describing this protein', max_length=1024)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excerpt_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='protein',
            name='blurb',
            field=models.TextField(blank=True, help_text='Brief descriptive blurb', max_length=512),
        ),
        migrations.AddField(
            model_name='excerpt',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to='proteins.Protein'),
        ),
        migrations.AddField(
            model_name='excerpt',
            name='reference',
            field=models.ForeignKey(help_text='Source of this excerpt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excerpt', to='references.Reference'),
        ),
        migrations.AddField(
            model_name='excerpt',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excerpt_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
