# Generated by Django 2.1.2 on 2018-11-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0030_lineage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excerpt",
            name="content",
            field=models.TextField(help_text="Brief excerpt describing this protein", max_length=1200),
        ),
    ]
