# Generated by Django 2.1.2 on 2018-12-16 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0042_auto_20181216_1744"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="excerpt",
            name="protein",
        ),
    ]
