# Generated by Django 2.1.7 on 2019-03-22 00:59

from django.db import migrations, models
from proteins.models.protein import prot_uuid
import uuid as uuid_lib


def forwards_func(apps, schema_editor):
    Protein = apps.get_model("proteins", "Protein")
    for instance in Protein.objects.all():
        instance.uuid = prot_uuid(5)
        instance.save()


def reverse_func(apps, schema_editor):
    Protein = apps.get_model("proteins", "Protein")
    for instance in Protein.objects.all():
        instance.uuid = uuid_lib.uuid4()
        instance.save()


def stub(a, b):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0047_auto_20190319_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(stub, reverse_func),
        migrations.RemoveField(
            model_name='protein',
            name='uuid',
        ),
        migrations.AddField(
            model_name='protein',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(forwards_func, stub),
        migrations.AlterField(
            model_name='protein',
            name='uuid',
            field=models.CharField(db_index=True, default=prot_uuid, editable=False, max_length=5, unique=True),
        ),
    ]
