# Generated by Django 2.1.7 on 2019-03-23 19:47

from django.db import migrations, models

import proteins.models.protein


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0048_change_protein_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default=proteins.models.protein.prot_uuid,
                editable=False,
                max_length=5,
                unique=True,
                verbose_name="FPbase ID",
            ),
        ),
    ]
