# Generated by Django 2.2.2 on 2019-07-14 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("proteins", "0049_auto_20190323_1947")]

    operations = [
        migrations.AddField(
            model_name="spectrum",
            name="source",
            field=models.CharField(blank=True, help_text="Source of the spectra data", max_length=128),
        ),
        migrations.AlterField(
            model_name="lineage",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="lineage",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="lineage",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="osermeasurement",
            name="percent",
            field=models.FloatField(
                blank=True,
                help_text="Percentage of 'normal' looking cells",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Percent Normal Cells",
            ),
        ),
        migrations.AlterField(
            model_name="protein",
            name="agg",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Monomer"),
                    ("d", "Dimer"),
                    ("td", "Tandem dimer"),
                    ("wd", "Weak dimer"),
                    ("t", "Tetramer"),
                ],
                help_text="Oligomerization tendency",
                max_length=2,
                verbose_name="Oligomerization",
            ),
        ),
    ]
