# Generated by Django 4.2.1 on 2024-10-01 16:26

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("proteins", "0054_microscope_cfg_calc_efficiency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectrum",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("approved", "approved"),
                    ("pending", "pending"),
                    ("rejected", "rejected"),
                ],
                default="approved",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="spectrum",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="status",
                verbose_name="status changed",
            ),
        ),
    ]
