# Generated by Django 4.2.24 on 2025-09-04 16:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0055_spectrum_status_spectrum_status_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='full_well_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Full well capacity in electrons', null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='pixel_size',
            field=models.FloatField(blank=True, help_text="Pixel size in microns e.g. '6.5'.  (assumes square pixels)", null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AddField(
            model_name='camera',
            name='pixels_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='pixels_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CameraMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'HCG 12-bit fast', 'LCG 16-bit slow', 'EM gain 300'", max_length=128)),
                ('adc_bit_depth', models.PositiveIntegerField(blank=True, help_text='e.g. 12, 14, 16', null=True)),
                ('readout_rate_mhz', models.FloatField(blank=True, help_text='Pixel clock / ADC rate (MHz) if applicable', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature_setpoint_c', models.FloatField(blank=True, help_text='Cooling setpoint (°C). Dark current depends on this.', null=True)),
                ('dark_current', models.FloatField(blank=True, help_text='Electrons/pixel/second at the stated temperature', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('read_noise_median', models.FloatField(blank=True, help_text='e- median', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('read_noise_rms', models.FloatField(blank=True, help_text='e- RMS', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('frame_rate', models.FloatField(blank=True, help_text='Max full-chip FPS under this mode.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='proteins.camera')),
            ],
            options={
                'indexes': [models.Index(fields=['camera', 'name'], name='proteins_ca_camera__0953d7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cameramode',
            constraint=models.UniqueConstraint(fields=('camera', 'name'), name='unique_camera_mode'),
        ),
    ]
