# Generated by Claude Code on 2025-11-10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0057_add_status_index'),
        ('references', '0008_alter_reference_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='spectrum',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(
                        owner_state__isnull=False,
                        owner_dye__isnull=True,
                        owner_filter__isnull=True,
                        owner_light__isnull=True,
                        owner_camera__isnull=True,
                    )
                    | models.Q(
                        owner_state__isnull=True,
                        owner_dye__isnull=False,
                        owner_filter__isnull=True,
                        owner_light__isnull=True,
                        owner_camera__isnull=True,
                    )
                    | models.Q(
                        owner_state__isnull=True,
                        owner_dye__isnull=True,
                        owner_filter__isnull=False,
                        owner_light__isnull=True,
                        owner_camera__isnull=True,
                    )
                    | models.Q(
                        owner_state__isnull=True,
                        owner_dye__isnull=True,
                        owner_filter__isnull=True,
                        owner_light__isnull=False,
                        owner_camera__isnull=True,
                    )
                    | models.Q(
                        owner_state__isnull=True,
                        owner_dye__isnull=True,
                        owner_filter__isnull=True,
                        owner_light__isnull=True,
                        owner_camera__isnull=False,
                    )
                ),
                name='spectrum_exactly_one_owner',
                violation_error_message='Spectrum must have exactly one owner (state, dye, filter, light, or camera)',
            ),
        ),
    ]
