# Generated by Django 5.2.7 on 2025-11-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0057_add_status_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapGenePlasmid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plasmid_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("size", models.IntegerField(blank=True, help_text="Size in base pairs", null=True)),
                ("topology", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "SnapGene Plasmid",
                "verbose_name_plural": "SnapGene Plasmids",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="protein",
            name="snapgene_plasmids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Associated SnapGene plasmids",
                related_name="proteins",
                to="proteins.snapgeneplasmid",
            ),
        ),
    ]
