# Generated by Django 5.2.8 on 2026-01-06 16:25

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0060_spectrum_optimized_storage'),
        ('references', '0009_curve_data_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BleachCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='approved', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('x_values', models.BinaryField(help_text='X values as float32 binary array')),
                ('y_values', models.BinaryField(help_text='Y values as float32 binary array')),
                ('x_min', models.FloatField(blank=True, help_text='Minimum X value', null=True)),
                ('x_max', models.FloatField(blank=True, help_text='Maximum X value', null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the curve data', max_length=128)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or conditions')),
                ('bleach_measurement', models.ForeignKey(help_text='BleachMeasurement this curve belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='curves', to='proteins.bleachmeasurement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_curves', to='references.reference')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bleach Curve',
                'verbose_name_plural': 'Bleach Curves',
                'indexes': [models.Index(fields=['bleach_measurement_id', 'status'], name='bleachcurve_meas_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaturationCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='approved', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('x_values', models.BinaryField(help_text='X values as float32 binary array')),
                ('y_values', models.BinaryField(help_text='Y values as float32 binary array')),
                ('x_min', models.FloatField(blank=True, help_text='Minimum X value', null=True)),
                ('x_max', models.FloatField(blank=True, help_text='Maximum X value', null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the curve data', max_length=128)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or conditions')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in °C during maturation measurement', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_curves', to='references.reference')),
                ('state', models.ForeignKey(help_text='Protein state this curve belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='maturation_curves', to='proteins.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maturation Curve',
                'verbose_name_plural': 'Maturation Curves',
                'indexes': [models.Index(fields=['state_id', 'status'], name='matcurve_state_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='PKACurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='approved', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('x_values', models.BinaryField(help_text='X values as float32 binary array')),
                ('y_values', models.BinaryField(help_text='Y values as float32 binary array')),
                ('x_min', models.FloatField(blank=True, help_text='Minimum X value', null=True)),
                ('x_max', models.FloatField(blank=True, help_text='Maximum X value', null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the curve data', max_length=128)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or conditions')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_curves', to='references.reference')),
                ('state', models.ForeignKey(help_text='Protein state this curve belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pka_curves', to='proteins.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pKa Curve',
                'verbose_name_plural': 'pKa Curves',
                'indexes': [models.Index(fields=['state_id', 'status'], name='pkacurve_state_status_idx')],
            },
        ),
    ]
