# Generated by Django 5.2.17 on 2026-09-20 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0060_spectrum_optimized_storage'),
        ('references', '0009_alter_reference_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='spectrum',
            name='spectrum_unique_owner_subtype',
        ),
        migrations.AddConstraint(
            model_name='spectrum',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('owner_fluor', 'subtype'), name='spectrum_unique_approved_fluor_subtype', violation_error_message='This fluorophore already has an approved spectrum of this type'),
        ),
    ]
