# Generated by Django 5.2.17 on 2026-09-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0062_delete_spectrumless_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='source',
            field=models.CharField(blank=True, help_text='Source of the spectra data', max_length=200),
        ),
    ]
