# Generated by Django 5.2.17 on 2026-10-01 07:53

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0063_spectrum_source_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('[<>]', 'Angle brackets are not allowed', inverse_match=True)]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the fluorescent protein', max_length=128, validators=[django.core.validators.RegexValidator('[<>]', 'Angle brackets are not allowed', inverse_match=True)]),
        ),
    ]
