# Generated by Django 5.2.17 on 2026-10-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0064_protein_name_alias_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commons_file', models.CharField(blank=True, help_text="Wikimedia Commons file name, without the 'File:' prefix. Leave blank to use an uploaded image instead.", max_length=255)),
                ('image', models.ImageField(blank=True, height_field='height', help_text='Uploaded image, used only when there is no Commons file.', upload_to='organism_photos/', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Original width (px)', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Original height (px)', null=True)),
                ('author', models.CharField(max_length=255)),
                ('license', models.CharField(help_text="e.g. 'CC BY-SA 4.0' or 'Public domain'", max_length=64)),
                ('license_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True, help_text='Page describing the original image.')),
                ('pictured', models.CharField(blank=True, help_text="Scientific name of the pictured organism, if it is not exactly this taxon (e.g. a named species standing in for an 'sp.' record).", max_length=128)),
                ('pictured_note', models.CharField(blank=True, help_text="How `pictured` relates, e.g. 'same genus' or 'synonym'.", max_length=64)),
                ('alt', models.CharField(blank=True, help_text='Description for screen readers.', max_length=255)),
                ('organism', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='proteins.organism')),
            ],
            options={
                'verbose_name': 'Organism photo',
            },
        ),
    ]
