# Generated by Django 1.11.9 on 2018-03-12 01:56

import django.core.validators
from django.db import migrations, models

import proteins.fields


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="twop_ex_max",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(700),
                    django.core.validators.MaxValueValidator(1600),
                ],
                verbose_name="Peak 2P excitation",
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="twop_ex_spectra",
            field=proteins.fields.SpectrumField(
                blank=True, help_text="List of [[wavelength, value],...] pairs", null=True
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="twop_peakGM",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Peak 2P cross-section of S0->S1 (GM)",
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="twop_qy",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)],
                verbose_name="2P Quantum Yield",
            ),
        ),
    ]
