# Generated by Django 1.11.9 on 2018-03-15 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0003_protein_oser"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fretpair",
            unique_together={("donor", "acceptor")},
        ),
    ]
