# Generated by Django 1.11.9 on 2018-04-03 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0006_auto_20180401_2009"),
    ]

    operations = [
        migrations.AddField(
            model_name="filter",
            name="aoi",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)],
            ),
        ),
        migrations.AddField(
            model_name="filter",
            name="bandcenter",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(200),
                    django.core.validators.MaxValueValidator(1600),
                ],
            ),
        ),
        migrations.AddField(
            model_name="filter",
            name="bandwidth",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(900),
                ],
            ),
        ),
        migrations.AddField(
            model_name="filter",
            name="edge",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="filter",
            name="tavg",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(900),
                ],
            ),
        ),
    ]
