# Generated by Django 1.11.9 on 2018-04-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0007_auto_20180403_0140"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="filter",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="light",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="spectrum",
            name="category",
            field=models.CharField(
                choices=[("d", "Dye"), ("p", "Protein"), ("l", "Light Source"), ("f", "Filter"), ("c", "Camera")],
                db_index=True,
                max_length=1,
                verbose_name="Item Type",
            ),
        ),
        migrations.AlterField(
            model_name="spectrum",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ex", "excitation"),
                    ("ab", "absorption"),
                    ("em", "emission"),
                    ("2p", "two photon absorption"),
                    ("bx", "bandpass (excitation)"),
                    ("bm", "bandpass (emission)"),
                    ("sp", "shortpass"),
                    ("lp", "longpass"),
                    ("bs", "beamsplitter"),
                    ("qe", "Quantum Efficiency"),
                    ("pd", "Power Distribution"),
                ],
                db_index=True,
                max_length=2,
                verbose_name="Spectra Subtype",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="slug",
            field=models.SlugField(help_text="Unique slug for the %(class)", max_length=128, unique=True),
        ),
    ]
