# Generated by Django 2.0.9 on 2018-10-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0023_spectrum_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bleachmeasurement",
            name="temp",
            field=models.FloatField(blank=True, null=True, verbose_name="Temp (˚C)"),
        ),
        migrations.AlterField(
            model_name="bleachmeasurement",
            name="units",
            field=models.CharField(blank=True, help_text="e.g. W/cm2", max_length=100, verbose_name="Power Units"),
        ),
    ]
