# Generated by Django 2.0.9 on 2018-10-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0025_auto_20181011_1715"),
    ]

    operations = [
        migrations.AddField(
            model_name="bleachmeasurement",
            name="cell_type",
            field=models.CharField(blank=True, help_text="e.g. HeLa", max_length=60, verbose_name="Cell Type"),
        ),
    ]
