# Generated by Django 2.1.2 on 2018-12-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0035_auto_20181110_0103"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineage",
            name="root_node",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descendants",
                to="proteins.Lineage",
                verbose_name="Root Node",
            ),
        ),
    ]
