# Generated by Django 2.1.2 on 2018-12-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0039_auto_20181206_0009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="cofactor",
            field=models.CharField(
                blank=True,
                choices=[("br", "Bilirubin"), ("bv", "Biliverdin"), ("fl", "Flavin"), ("pc", "Phycocyanobilin")],
                help_text="Required for fluorescence",
                max_length=2,
            ),
        ),
    ]
