# Generated by Django 2.1.2 on 2018-12-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0040_auto_20181210_0345"),
    ]

    operations = [
        migrations.AddField(
            model_name="excerpt",
            name="proteins",
            field=models.ManyToManyField(related_name="excerpts", to="proteins.Protein"),
        ),
        migrations.AlterField(
            model_name="excerpt",
            name="protein",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="excerpt", to="proteins.Protein"
            ),
        ),
        migrations.AlterField(
            model_name="excerpt",
            name="reference",
            field=models.ForeignKey(
                help_text="Source of this excerpt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excerpts",
                to="references.Reference",
            ),
        ),
    ]
