# Generated by Django 4.2.1 on 2023-06-11 16:00

from django.db import migrations

import proteins.models.protein


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0052_alter_protein_chromophore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="chromophore",
            field=proteins.models.protein._NonNullChar(blank=True, default="", max_length=5),
        ),
    ]
