# Generated by Django 4.2.1 on 2023-11-27 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0053_alter_protein_chromophore"),
    ]

    operations = [
        migrations.AddField(
            model_name="microscope",
            name="cfg_calc_efficiency",
            field=models.BooleanField(default=True, help_text="Calculate efficiency on update."),
        ),
        migrations.AddField(
            model_name="microscope",
            name="cfg_enable_pan_zoom",
            field=models.BooleanField(default=True, help_text="Enable pan and zoom on spectra plot."),
        ),
        migrations.AddField(
            model_name="microscope",
            name="cfg_fill_area",
            field=models.BooleanField(default=True, help_text="Fill area under spectra."),
        ),
        migrations.AddField(
            model_name="microscope",
            name="cfg_max_wave",
            field=models.PositiveSmallIntegerField(
                default=800,
                help_text="Maximum wavelength to display on page load.",
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(1199),
                ],
            ),
        ),
        migrations.AddField(
            model_name="microscope",
            name="cfg_min_wave",
            field=models.PositiveSmallIntegerField(
                default=350,
                help_text="Minimum wavelength to display on page load.",
                validators=[
                    django.core.validators.MinValueValidator(300),
                    django.core.validators.MaxValueValidator(1199),
                ],
            ),
        ),
    ]
