# Generated by Django 5.2.7 on 2025-10-22 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0056_spectrum_spectrum_state_status_idx_and_more"),
        ("references", "0008_alter_reference_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="protein",
            index=models.Index(fields=["status"], name="protein_status_idx"),
        ),
    ]
