# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 01:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('family', models.CharField(max_length=80)),
                ('given', models.CharField(max_length=80)),
                ('initials', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('doi', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^10.\\d{4,9}/[-._;()/:a-zA-Z0-9]+$', 'Not a valid DOI string')], verbose_name='DOI')),
                ('pmid', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Pubmed ID')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('journal', models.CharField(blank=True, max_length=512)),
                ('pages', models.CharField(blank=True, max_length=20)),
                ('volume', models.CharField(blank=True, default='', max_length=10)),
                ('issue', models.CharField(blank=True, default='', max_length=10)),
                ('citation', models.CharField(blank=True, default='', max_length=256)),
                ('year', models.PositiveIntegerField(help_text='YYYY', validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2018)])),
                ('summary', models.CharField(blank=True, help_text='Brief summary of findings', max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_idx', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.Author')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.Reference')),
            ],
            options={
                'ordering': ['author_idx'],
            },
        ),
        migrations.AddField(
            model_name='reference',
            name='authors',
            field=models.ManyToManyField(through='references.ReferenceAuthor', to='references.Author'),
        ),
        migrations.AddField(
            model_name='reference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='publications',
            field=models.ManyToManyField(through='references.ReferenceAuthor', to='references.Reference'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set([('family', 'initials')]),
        ),
    ]
