# Generated by Django 2.0.7 on 2018-08-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_reference_firstauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('year',)},
        ),
    ]
