# Generated by Django 5.2.8 on 2026-01-06 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_alter_reference_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.PositiveIntegerField(help_text='YYYY', validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
