# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='seq',
            field=models.CharField(blank=True, help_text='Amino acid sequence (leave blank if not confident)', max_length=512, null=True, unique=True),
        ),
    ]
