# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 03:46
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
            TrigramExtension(),
    ]
