# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0002_auto_20171113_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='additional_references',
            field=models.ManyToManyField(blank=True, related_name='protein_additional_reference', to='references.Reference', verbose_name='Additional References'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='default_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_protein', to='proteins.State'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='primary_reference',
            field=models.ForeignKey(blank=True, help_text='Preferably the publication that introduced the protein', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protein_primary_reference', to='references.Reference', verbose_name='Primary Reference'),
        ),
    ]
