# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 18:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import proteins.models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0002_auto_20171216_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='seq',
            field=models.CharField(blank=True, help_text='Amino acid sequence (IPG ID is preferred)', max_length=512, null=True, unique=True, validators=[django.core.validators.RegexValidator('^acdefghiklmnpqrstvwyACDEFGHIKLMNPQRSTVWY$', 'Protein sequence contains invalid letters.')]),
        ),
        migrations.AlterField(
            model_name='state',
            name='em_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='state',
            name='em_spectra',
            field=proteins.models.SpectrumField(blank=True, help_text='Spectrum information as a list of [wavelength, value] pairs, e.g. [[300, 0.5], [301, 0.6],... ]', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='ex_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AlterField(
            model_name='state',
            name='ex_spectra',
            field=proteins.models.SpectrumField(blank=True, help_text='Spectrum information as a list of [wavelength, value] pairs, e.g. [[300, 0.5], [301, 0.6],... ]', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='ext_coeff',
            field=models.IntegerField(blank=True, help_text='Extinction Coefficient', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300000)]),
        ),
        migrations.AlterField(
            model_name='state',
            name='lifetime',
            field=models.FloatField(blank=True, help_text='Fluorescence Lifetime (ns)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='state',
            name='maturation',
            field=models.FloatField(blank=True, help_text='Maturation time (min)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1400)]),
        ),
        migrations.AlterField(
            model_name='state',
            name='pka',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)], verbose_name='pKa'),
        ),
        migrations.AlterField(
            model_name='state',
            name='qy',
            field=models.FloatField(blank=True, help_text='Quantum Yield', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
