# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proteins', '0002_auto_20180109_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='bleachmeasurement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bleachmeasurement_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bleachmeasurement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bleachmeasurement_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fretpair',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fretpair_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fretpair',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fretpair_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='protein',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protein_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='protein',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protein_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
