# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0003_auto_20171113_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_wave', models.IntegerField(blank=True, help_text="Wavelength of light that drives the protein into the 'To state:' (if applicable)", null=True, verbose_name='Transition Wavelength')),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='to_state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='trans_wave',
        ),
        migrations.AddField(
            model_name='statetransition',
            name='from_state',
            field=models.ForeignKey(help_text='The initial state required for this transition to occur', on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='proteins.State', verbose_name='From state'),
        ),
        migrations.AddField(
            model_name='statetransition',
            name='to_state',
            field=models.ForeignKey(blank=True, help_text="The state to which this state transitions upon 'transition wavelength' illumination", on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='proteins.State', verbose_name='To state'),
        ),
        migrations.AddField(
            model_name='state',
            name='transitions',
            field=models.ManyToManyField(blank=True, related_name='transition_state', through='proteins.StateTransition', to='proteins.State', verbose_name='State Transitions'),
        ),
    ]
