# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proteins', '0003_auto_20180109_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Protein Collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='protein',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='proteins', to='references.Reference'),
        ),
        migrations.AddField(
            model_name='proteincollection',
            name='proteins',
            field=models.ManyToManyField(related_name='collection_memberships', to='proteins.Protein'),
        ),
    ]
