# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_auto_20171114_0427'),
        ('proteins', '0004_auto_20171114_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='additional_references',
        ),
        migrations.AddField(
            model_name='protein',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='proteins', to='references.Reference', verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='primary_reference',
            field=models.ForeignKey(blank=True, help_text='Preferably the publication that introduced the protein', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_proteins', to='references.Reference', verbose_name='Primary Reference'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='seq',
            field=models.CharField(blank=True, help_text='Amino acid sequence', max_length=512, unique=True),
        ),
    ]
