# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 03:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0004_auto_20180110_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='default_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for', to='proteins.State'),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='from_state',
            field=models.ForeignKey(help_text='The initial state ', on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='proteins.State', verbose_name='From state'),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='to_state',
            field=models.ForeignKey(help_text='The state after transition', on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='proteins.State', verbose_name='To state'),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='trans_wave',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Wavelength required', null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(1000)], verbose_name='Transition Wavelength'),
        ),
    ]
