# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 20:57
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import proteins.models.spectrum


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proteins', '0005_auto_20180328_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data', proteins.models.spectrum.SpectrumData(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=10), size=2), size=None)),
                ('state',  models.ForeignKey(blank=True, null=True, to='proteins.State', related_name="spectra", help_text="The protein(state) to which this spectrum belongs", on_delete=django.db.models.deletion.SET_NULL)),
                ('stype', models.CharField(blank=True, choices=[('ex', 'excitation'), ('abs', 'absorption'), ('em', 'emission'), ('twop', 'two photon absorption')], max_length=4, verbose_name='Spectra Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spectrum_author', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spectrum_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='state',
            name='em_spectra_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_em', to='proteins.Spectrum'),
        ),
        migrations.AddField(
            model_name='state',
            name='ex_spectra_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_ex', to='proteins.Spectrum'),
        ),
        migrations.AddField(
            model_name='state',
            name='twop_spectra_fk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_twop', to='proteins.Spectrum'),
        ),
    ]
