# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0005_auto_20171118_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='seq',
            field=models.CharField(blank=True, help_text='Amino acid sequence', max_length=512, null=True, unique=True),
        ),
    ]
