# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 04:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0005_auto_20171230_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='em_max',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='state',
            name='ex_max',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)]),
        ),
    ]
