# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 03:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0005_auto_20180112_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
