# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0006_auto_20171231_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='tax_id',
            field=models.CharField(help_text='NCBI Taxonomy ID (e.g. 6100 for Aequorea victora)', max_length=8, unique=True, verbose_name='Taxonomy ID'),
        ),
    ]
