# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def move_spectra(apps, schema_editor):
    States = apps.get_model("proteins", "State")
    Spectrum = apps.get_model("proteins", "Spectrum")
    for state in States.objects.all():
        if state.ex_spectra:
            spectrumx = Spectrum(
                data=state.ex_spectra.data,
                state=state,
                stype='ex'
            )
            spectrumx.save()
            state.ex_spectra_fk = spectrumx
        if state.em_spectra:
            spectrumm = Spectrum(
                data=state.em_spectra.data,
                state=state,
                stype='em'
            )
            spectrumm.save()
            state.em_spectra_fk = spectrumm
        if state.twop_ex_spectra:
            spectrum = Spectrum(
                data=state.twop_ex_spectra.data,
                state=state,
                stype='twop'
            )
            spectrum.save()
            state.twop_spectra_fk = spectrum
        state.save()


def undo_move_spectra(apps, schema_editor):
    pass
    Spectrum = apps.get_model("proteins", "Spectrum")
    for spectrum in Spectrum.objects.all():
        if spectrum.stype and spectrum.state:
            if spectrum.stype == 'ex':
                spectrum.state.ex_spectra = spectrum.data
            elif spectrum.stype == 'em':
                spectrum.state.em_spectra = spectrum.data
            elif spectrum.stype == 'twop':
                spectrum.state.twop_ex_spectra = spectrum.data


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proteins', '0006_auto_20180328_2057'),
    ]

    operations = [
        migrations.RunPython(move_spectra, undo_move_spectra),
    ]
