# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0006_protein_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='chromophore',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
