# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0006_auto_20171118_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetransition',
            name='protein',
            field=models.ForeignKey(default=None, help_text='The protein that demonstrates this transition', on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='proteins.Protein', verbose_name='Protein Transitioning'),
            preserve_default=False,
        ),
    ]
