# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0007_migrate_spectra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='em_spectra',
        ),
        migrations.RemoveField(
            model_name='state',
            name='ex_spectra',
        ),
        migrations.RemoveField(
            model_name='state',
            name='twop_ex_spectra',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='ex_spectra_fk',
            new_name='ex_spectra',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='em_spectra_fk',
            new_name='em_spectra',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='twop_spectra_fk',
            new_name='twop_spectra',
        ),

    ]
