# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0007_auto_20171231_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={'ordering': ['scientific_name'], 'verbose_name': 'Organism'},
        ),
        migrations.AddField(
            model_name='organism',
            name='rank',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
