# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0007_statetransition_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='ipg_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
