# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 20:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0007_protein_chromophore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None, validators=[django.core.validators.RegexValidator('^[ACDEFGHIKLMNPQRSTVWY-][1-9][0-9]{0,2}[ACDEFGHIKLMNPQRSTVWY]$', 'not a valid mutation code: eg S65T')])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='proteins.Protein', verbose_name='Parent Protein')),
            ],
        ),
    ]
