# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0008_auto_20171231_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='tax_id',
            field=models.CharField(help_text='NCBI Taxonomy ID (e.g. 6100 for Aequorea victora)', max_length=8, verbose_name='Taxonomy ID'),
        ),
    ]
