# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:27
from __future__ import unicode_literals

from django.db import migrations
from decimal import Decimal

def move_bleach_field(apps, schema_editor):
	# bleach data has moved to it's own model
	# this will move the bleach_wide and bleach_conf data
	State = apps.get_model('proteins', 'State')
	BleachMeasurement = apps.get_model('proteins', 'BleachMeasurement')
	for state in State.objects.all():
		if state.bleach_wide and not Decimal.is_nan(state.bleach_wide):
			bm = BleachMeasurement(
					rate=state.bleach_wide,
					state=state
			)
			bm.save()
		if state.bleach_conf and not Decimal.is_nan(state.bleach_conf):
			bm = BleachMeasurement(
					rate=state.bleach_conf,
					state=state
			)
			bm.save()
		state.bleach_wide = None
		state.bleach_conf = None
		state.save()


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0009_bleachmeasurement'),
    ]

    operations = [
	    migrations.RunPython(move_bleach_field),
    ]
