# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-02 21:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0009_auto_20180102_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='bleachmeasurement',
            name='power',
            field=models.FloatField(blank=True, help_text='Illumination power (W/cm2)', null=True, verbose_name='Illumination Power'),
        ),
        migrations.AlterField(
            model_name='state',
            name='lifetime',
            field=models.FloatField(blank=True, help_text='Lifetime (ns)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
