# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proteins', '0010_auto_20180116_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteincollection',
            name='private',
            field=models.BooleanField(default=False, help_text='Private collections can not be seen by or shared with other users', verbose_name='Private Collection'),
        ),
        migrations.AlterUniqueTogether(
            name='proteincollection',
            unique_together=set([('owner', 'name')]),
        ),
    ]
