# Generated by Django 2.0.6 on 2018-06-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0012_auto_20180624_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microscope',
            name='bs_filters',
            field=models.ManyToManyField(blank=True, related_name='as_bs_filter', to='proteins.Filter'),
        ),
        migrations.AlterField(
            model_name='microscope',
            name='cameras',
            field=models.ManyToManyField(blank=True, related_name='microscopes', to='proteins.Camera'),
        ),
        migrations.AlterField(
            model_name='microscope',
            name='em_filters',
            field=models.ManyToManyField(blank=True, related_name='as_em_filter', to='proteins.Filter'),
        ),
        migrations.AlterField(
            model_name='microscope',
            name='ex_filters',
            field=models.ManyToManyField(blank=True, related_name='as_ex_filter', to='proteins.Filter'),
        ),
        migrations.AlterField(
            model_name='microscope',
            name='lights',
            field=models.ManyToManyField(blank=True, related_name='microscopes', to='proteins.Light'),
        ),
    ]
