# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 02:50
from __future__ import unicode_literals

from django.db import migrations


def transfer_timestamp(apps, schema_editor):
    # bleach data has moved to it's own model
    # this will move the bleach_wide and bleach_conf data
    MODELS = []
    MODELS.append(apps.get_model('proteins', 'Organism'))
    MODELS.append(apps.get_model('proteins', 'State'))
    MODELS.append(apps.get_model('proteins', 'Protein'))
    MODELS.append(apps.get_model('proteins', 'StateTransition'))
    MODELS.append(apps.get_model('proteins', 'FRETpair'))

    for model in MODELS:
        for instance in model.objects.all():
            instance.created = instance.created_at
            instance.modified = instance.updated_at
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0012_auto_20171205_0250'),
    ]

    operations = [
        migrations.RunPython(transfer_timestamp),
    ]
