# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0013_auto_20171205_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fretpair',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fretpair',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='state',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='state',
            name='updated_at',
        ),
    ]
