# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0013_auto_20180118_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bleachmeasurement',
            name='units',
            field=models.CharField(blank=True, help_text='e.g. W/cm2', max_length=100, verbose_name='Power Unit'),
        ),
        migrations.AlterField(
            model_name='bleachmeasurement',
            name='modality',
            field=models.CharField(blank=True, choices=[('ps', 'Point Scanning Confocal'), ('sd', 'Spinning Disc Confocal'), ('wf', 'Widefield'), ('t', 'TIRF'), ('s', 'Spectrophotometer'), ('o', 'Other')], help_text='Type of imaging used', max_length=2, verbose_name='Illumination Modality'),
        ),
        migrations.AlterField(
            model_name='bleachmeasurement',
            name='power',
            field=models.FloatField(blank=True, null=True, verbose_name='Illumination Power'),
        ),
        migrations.AlterField(
            model_name='bleachmeasurement',
            name='rate',
            field=models.FloatField(help_text='Photobleaching half-life', verbose_name='Bleach Rate'),
        ),
    ]
