# Generated by Django 2.0.6 on 2018-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0013_auto_20180716_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterplacement',
            name='path',
            field=models.CharField(choices=[('ex', 'Excitation Path'), ('em', 'Emission Path'), ('bs', 'Both Paths')], max_length=2, verbose_name='Ex/Em Path'),
        ),
    ]
