# Generated by Django 2.0.6 on 2018-07-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0013_auto_20180702_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticalconfig',
            name='bs_filters',
            field=models.ManyToManyField(blank=True, related_name='as_ocbs', to='proteins.Filter'),
        ),
        migrations.AddField(
            model_name='opticalconfig',
            name='em_filters',
            field=models.ManyToManyField(blank=True, related_name='as_ocem', to='proteins.Filter'),
        ),
        migrations.AddField(
            model_name='opticalconfig',
            name='ex_filters',
            field=models.ManyToManyField(blank=True, related_name='as_ocex', to='proteins.Filter'),
        ),
    ]
