# Generated by Django 2.0.6 on 2018-07-01 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0013_auto_20180629_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='light',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='microscope',
            name='configs',
            field=models.ManyToManyField(blank=True, related_name='microscope_memberships', to='proteins.OpticalConfig'),
        ),
        migrations.AlterField(
            model_name='opticalconfig',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optical_configs', to='proteins.Camera'),
        ),
        migrations.AlterField(
            model_name='opticalconfig',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='optical_configs', through='proteins.FilterPlacement', to='proteins.Filter'),
        ),
        migrations.AlterField(
            model_name='opticalconfig',
            name='light',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optical_configs', to='proteins.Light'),
        ),
        migrations.AlterUniqueTogether(
            name='microscope',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='opticalconfig',
            unique_together=set(),
        ),
    ]
