# Generated by Django 2.0.6 on 2018-07-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0014_auto_20180703_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opticalconfig',
            name='bs_filters',
        ),
        migrations.RemoveField(
            model_name='opticalconfig',
            name='em_filters',
        ),
        migrations.RemoveField(
            model_name='opticalconfig',
            name='ex_filters',
        ),
    ]
