# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0014_auto_20180124_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='bleachmeasurement',
            name='fusion',
            field=models.CharField(blank=True, help_text='(if applicable)', max_length=60, verbose_name='Fusion Protein'),
        ),
        migrations.AddField(
            model_name='bleachmeasurement',
            name='in_cell',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (-1, 'Unkown')], default=0, help_text='measurement was performed inside living cells', verbose_name='In cells?'),
        ),
        migrations.AddField(
            model_name='bleachmeasurement',
            name='light',
            field=models.CharField(blank=True, choices=[('a', 'Arc-lamp'), ('la', 'Laser'), ('le', 'LED'), ('o', 'Other')], max_length=2, verbose_name='Light Source'),
        ),
        migrations.AddField(
            model_name='bleachmeasurement',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='bleachmeasurement',
            name='modality',
            field=models.CharField(blank=True, choices=[('wf', 'Widefield'), ('ps', 'Point Scanning Confocal'), ('sd', 'Spinning Disc Confocal'), ('s', 'Spectrophotometer'), ('t', 'TIRF'), ('o', 'Other')], max_length=2, verbose_name='Imaging Modality'),
        ),
        migrations.AlterField(
            model_name='bleachmeasurement',
            name='power',
            field=models.FloatField(blank=True, help_text="If not reported, use '-1'", null=True, verbose_name='Illumination Power'),
        ),
        migrations.AlterField(
            model_name='bleachmeasurement',
            name='rate',
            field=models.FloatField(help_text='Photobleaching half-life (s)', verbose_name='Bleach Rate'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='parent_organism',
            field=models.ForeignKey(blank=True, help_text='Organism from which the protein was engineered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proteins', to='proteins.Organism', verbose_name='Parental organism'),
        ),
    ]
