# Generated by Django 2.0.6 on 2018-07-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0015_auto_20180704_2235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opticalconfig',
            unique_together={('name', 'microscope')},
        ),
    ]
