# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import proteins.models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0016_auto_20171206_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='default',
        ),
        migrations.AddField(
            model_name='state',
            name='is_dark',
            field=models.BooleanField(default=False, help_text='Dark state, exhibiting no fluorescence', verbose_name='Dark State'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the fluorescent protein', max_length=128),
        ),
        migrations.AlterField(
            model_name='state',
            name='em_spectra',
            field=proteins.models.SpectrumField(blank=True, help_text='Enter spectrum information as a list of (wavelength, value) pairs, e.g. [(300, 0.5), (301, 0.6),... ]', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='ex_spectra',
            field=proteins.models.SpectrumField(blank=True, help_text='Enter spectrum information as a list of (wavelength, value) pairs, e.g. [(300, 0.5), (301, 0.6),... ]', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='lifetime',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fluorescence Lifetime (nanoseconds)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='maturation',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maturation time (seconds)', max_digits=5, null=True),
        ),
    ]
