# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0017_auto_20171206_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='state_id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='state_name',
        ),
        migrations.AddField(
            model_name='state',
            name='name',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='slug', help_text='Unique slug for the state', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='is_dark',
            field=models.BooleanField(default=False, help_text='This is a dark state, exhibiting no fluorescence', verbose_name='Dark State'),
        ),
    ]
