# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0019_auto_20171206_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bleachmeasurement',
            name='rate',
            field=models.FloatField(help_text='Photobleaching rate', verbose_name='Bleach Rate'),
        ),
        migrations.AlterField(
            model_name='fretpair',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='mw',
            field=models.FloatField(blank=True, help_text='Molecular Weight', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='lifetime',
            field=models.FloatField(blank=True, help_text='Fluorescence Lifetime (nanoseconds)', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='maturation',
            field=models.FloatField(blank=True, help_text='Maturation time (seconds)', null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='pka',
            field=models.FloatField(blank=True, null=True, verbose_name='pKa'),
        ),
        migrations.AlterField(
            model_name='state',
            name='qy',
            field=models.FloatField(blank=True, help_text='Quantum Yield', null=True),
        ),
    ]
