# Generated by Django 2.1.2 on 2018-12-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0038_auto_20181205_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='dye',
            name='emhex',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='dye',
            name='exhex',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='state',
            name='emhex',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='state',
            name='exhex',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
