# Generated by Django 4.2.1 on 2023-06-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proteins", "0051_alter_bleachmeasurement_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="chromophore",
            field=models.CharField(blank=True, default="", max_length=5),
        ),
    ]
