# Generated by Django 4.2 on 2023-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("favit", "0002_auto_20180113_0002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
