# Generated by Django 2.1.2 on 2019-01-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlogin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
