# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=4)),
                ('last_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(db_column='pmid', max_length=15, unique=True, verbose_name='PMID')),
                ('doi', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='DOI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('journal', models.CharField(blank=True, max_length=512)),
                ('pages', models.CharField(blank=True, max_length=20)),
                ('volume', models.CharField(blank=True, max_length=10)),
                ('pubdate', models.DateTimeField()),
                ('so', models.CharField(blank=True, max_length=128, verbose_name='SO')),
                ('ref', models.CharField(blank=True, max_length=512, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_idx', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.Author')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.Reference')),
            ],
            options={
                'ordering': ['author_idx'],
            },
        ),
        migrations.AddField(
            model_name='reference',
            name='authors',
            field=models.ManyToManyField(through='references.ReferenceAuthor', to='references.Author'),
        ),
        migrations.AddField(
            model_name='reference',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries_modifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='publications',
            field=models.ManyToManyField(through='references.ReferenceAuthor', to='references.Reference'),
        ),
    ]
