# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='citation',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
