# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 03:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='initials',
            new_name='given',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='pubdate',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='so',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reference',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='reference',
            name='issue',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reference',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='reference',
            name='year',
            field=models.PositiveIntegerField(default=1960, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2017)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(max_length=50, unique=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pmid',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Pubmed ID'),
        ),
    ]
