# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 13:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20180113_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.PositiveIntegerField(help_text='YYYY', validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4), django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
