# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20171216_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='given',
            field=models.CharField(max_length=80),
        ),
    ]
