# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20171114_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='pubdate',
            field=models.DateTimeField(blank=True),
        ),
    ]
