# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20171216_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='pmid',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Pubmed ID'),
        ),
    ]
