# Generated by Django 2.1.2 on 2018-10-26 15:47

from django.db import migrations, models


# NOTE: this adds a date field ... but all references should be resaved
# manually in order to populate it


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20180804_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='reference',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
