# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20171114_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='volume',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
