# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_auto_20180126_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='summary',
            field=models.CharField(blank=True, help_text='Brief summary of findings', max_length=512),
        ),
    ]
