# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 15:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_auto_20171216_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
