# Generated by Django 4.2 on 2023-05-14 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0005_auto_20190103_1409"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="year",
            field=models.PositiveIntegerField(
                help_text="YYYY",
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.MaxLengthValidator(4),
                    django.core.validators.MinValueValidator(1960),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="referenceauthor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
